solution/Adventureworks.WebMVC4/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StructureMap;
using Adventureworks.Domain5;
using Adventureworks.WebMVC4.Models;

namespace Adventureworks.WebMVC4.Controllers
{   
    public class ProductCategoryController : Controller
    {
		private readonly IProductCategoryRepository productcategoryRepository;
        private readonly IProductSubcategoryRepository productsubcategoryRepository;

        //// If you are using Dependency Injection, you can delete the following constructor
        //public ProductCategoryController() : this(new ProductCategoryRepository())
        //{
        //}

        public ProductCategoryController(IProductCategoryRepository productcategoryRepository)
        {
            this.productcategoryRepository = (IProductCategoryRepository)ObjectFactory.GetInstance(typeof(IProductCategoryRepository));
            this.productsubcategoryRepository = (IProductSubcategoryRepository)ObjectFactory.GetInstance(typeof(IProductSubcategoryRepository));
        }

        //
        // GET: /ProductCategory/

        //public ViewResult Index()
        //{
        //    return View(productcategoryRepository.AllIncluding(productcategory => productcategory.ProductSubcategories));
        //}

        [OutputCache(Duration = 10)]
        [ChildActionOnly]
        public ActionResult Index(int? subcategoryId)
        {
            ProductSubcategory prodSubcat = productsubcategoryRepository.Find(subcategoryId.GetValueOrDefault(1));
            var productCategories = productcategoryRepository.All;

            ViewBag.CurrentProductCategoryId = prodSubcat.ProductCategoryID;
            ViewBag.CurrentProductSubcategoryId = prodSubcat.ProductSubcategoryID;

            return PartialView(productCategories);
        }

        // GET: /Category/Browse/5
        public ActionResult Browse(string id)
        {
            return View();
        }

        //
        // GET: /ProductCategory/Details/5

        public ViewResult Details(int id)
        {
            return View(productcategoryRepository.Find(id));
        }

        //
        // GET: /ProductCategory/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /ProductCategory/Create

        [HttpPost]
        public ActionResult Create(ProductCategory productcategory)
        {
            if (ModelState.IsValid) {
                productcategoryRepository.InsertOrUpdate(productcategory);
                productcategoryRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }
        
        //
        // GET: /ProductCategory/Edit/5
 
        public ActionResult Edit(int id)
        {
             return View(productcategoryRepository.Find(id));
        }

        //
        // POST: /ProductCategory/Edit/5

        [HttpPost]
        public ActionResult Edit(ProductCategory productcategory)
        {
            if (ModelState.IsValid) {
                productcategoryRepository.InsertOrUpdate(productcategory);
                productcategoryRepository.Save();
                return RedirectToAction("Index");
            } else {
				return View();
			}
        }

        //
        // GET: /ProductCategory/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View(productcategoryRepository.Find(id));
        }

        //
        // POST: /ProductCategory/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            productcategoryRepository.Delete(id);
            productcategoryRepository.Save();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) {
                productcategoryRepository.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

solution/Adventureworks.WebMVC4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
         <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/ui-darkness")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")

    <script type="text/javascript">
        $(document).ready(function () {
            adjustMidColWidth();

            $(window).resize(function () {
                adjustMidColWidth();
            });
        });

        function adjustMidColWidth() {
            $("div.master-wrapper-center").width($(window).width() - 410);
            $("master-wrapper-cph").width($(window).width() - 435);
        }
    </script>
    </head>
    <body>
        <header>
            <div class="header">
                <div class="header-logo">
                    @{
                        //#if Full
                            <text><a class="logo">&nbsp; </a></text>
                        //#endif
                    }
                </div>
                @Html.Partial("_LoginPartial")
            </div>
            <div class="headermenu">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Purchasing", "Index", "Purchasing")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
            
        </header>
        <div class="master-wrapper-leftside">
                <div class="block block-category-navigation">
                    @{Html.RenderAction("Index", "ProductCategory");}
                </div>
        </div>
        <div id="body master-wrapper-center">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix master-wrapper-cph">
                @RenderBody()
            </section>
            <div class="master-wrapper-rightside">
                <div class="block-shoppingcart">
                    <div class="title">
                        Shopping Cart
                    </div>
                    <div class="clear">
                    </div>
                    <table id="bookingsList">
                        <tbody>
                            <tr class="cart">
                                <td class="cart-false" colspan="4">
                                    <span class="text">0 items in Cart...</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <footer>
            <div class="footer">
            <div class="footer-disclaimer">
                Updated to <a href="http://asp.net/mvc">ASP.NET MVC 4</a>
                <p>Originally developed by <a href="http://www.codeplex.com/site/users/view/supertigerzou">supertigerzou</a> with MVC 3</p>
                <p>Updated by <a href="http://www.codeplex.com/site/users/view/Bishops_move">Bishops_move</a></p></div>
        </div>
        </footer>

        
        @RenderSection("scripts", required: false)
    </body>
</html>