solution/Adventureworks.WebMVC3/Controllers/PurchasingController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.ComponentModel.Composition;
using Adventureworks.Domain;
using Adventureworks.Domain.Interfaces;
using Adventureworks.WebMVC3.PurchasingService;
using Adventureworks.FileRepository;

namespace Adventureworks.Web.Controllers
{
    public class PurchasingController : Controller
    {
        private readonly IPurchasingRepository _purchasingRepository;

        [ImportingConstructor]
        public PurchasingController(IPurchasingRepository purchasingRepository)
        {
            this._purchasingRepository = purchasingRepository;
        }

        //
        // GET: /Purchasing/

        public ActionResult Index()
        {
            IEnumerable<RequestForProposal> activeRfps = _purchasingRepository.RetrieveActive();

            return View(activeRfps);
        }

        public ActionResult CreateRfp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateRfp(RequestForProposal rfp)
        {
            IPurchasingService purchasingService = new PurchasingServiceClient();
            rfp.Status = "active";
            string[] invitedVendors = Request.Form["InvitedVendors"].Split(',');
            foreach (var invitedVendor in invitedVendors)
            {
                rfp.InvitedVendors.Add(VendorRepository.Retrieve(int.Parse(invitedVendor)));
            }

            try
            {
                SubmitPurchasingProposalResponse response = purchasingService.SubmitPurchasingProposal(new SubmitPurchasingProposalRequest(rfp));
            }
            catch (Exception)
            {
                
                throw;
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult VendorProposal(VendorSubmitProposalRequest svp)
        {
            IPurchasingService purchasingService = new PurchasingServiceClient();

            try
            {
                purchasingService.SubmitVendorProposal(new SubmitVendorProposalRequest(svp));
            }
            catch (Exception)
            {
                
                throw;
            }

            return RedirectToAction("Index");
        }

        public ActionResult VendorProposal(Guid id, int vendorId)
        {
            RequestForProposal rfp = _purchasingRepository.Retrieve(id);
            ViewBag.VendorId = vendorId;

            return View(rfp);
        }

        public ActionResult FinishedProposals()
        {
            IEnumerable<RequestForProposal> finishedRfps = _purchasingRepository.RetrieveFinished();

            return View(finishedRfps);
        }
    }
}

solution/Adventureworks.WebMVC3/Views/Purchasing/CreateRfp.cshtml
@model Adventureworks.Domain.RequestForProposal
@{
    ViewBag.Title = "CreateRfp";
    Layout = "~/Views/Shared/_CompactLayout.cshtml";
}
<h2>
    CreateRfp</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/ui.dropdownchecklist-1.1-min.js")" type="text/javascript"></script>

<script type="text/javascript">
    $(function () {
        $(".vendorList").dropdownchecklist({
            icon: {
                placement: 'right',
                toOpen: 'ui-icon-triangle-1-s',
                toClose: 'ui-icon-triangle-1-n'
            },
            width: 150
        });
    });
</script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>RequestForProposal</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.InvitedVendors)
        </div>
        <div class="editor-field">
            <select name="InvitedVendors" class="vendorList" multiple="multiple">
                <option value="1">Vendor 1</option>
                <option value="2">Vendor 2</option>
                <option value="3">Vendor 3</option>
                <option value="4">Vendor 4</option>
                <option value="5">Vendor 5</option>
                <option value="6">Vendor 6</option>
                <option value="7">Vendor 7</option>
                <option value="8">Vendor 8</option>
            </select>
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

solution/Adventureworks.WebMVC3/Views/Purchasing/FinishedProposals.cshtml
@using Adventureworks.Domain;
@model IEnumerable<RequestForProposal>
@{
    Layout = null;
}

<h2>
        Finished</h2>
<div>
    <table>
        <tr class="Header">
            <td>
                ID
            </td>
            <td>
                Title
            </td>
            <td>
                Created
            </td>
            <td>
                Status
            </td>
        </tr>
        @foreach (var rfp in Model)
        {
            <tr>
                <td>
                    @rfp.ID.ToString()
                </td>
                <td>
                    @rfp.Title
                </td>
                <td>
                    @rfp.CreationDate
                </td>
                <td>
                    @rfp.Status
                </td>
            </tr>
        }
    </table>
</div>

solution/Adventureworks.WebMVC3/Views/Purchasing/Index.cshtml
@using Adventureworks.Domain;
@model IEnumerable<RequestForProposal>
@{
    ViewBag.Title = "Index";
}
<script language="javascript" type="text/javascript">
    function showProposal(id) {
        var combo = document.getElementById('sel_' + id);
        if (combo.value == '') {
            document.location = '/Purchasing/VendorProposal?id=' + id;
        }
        else {
            document.location = '/Purchasing/VendorProposal?id=' + id + '&vendorId=' + combo.value;
        }
    }
</script>
<div>
    <input type="button" value="Create a new RFP" onclick="document.location='/Purchasing/CreateRfp'" />
    <input type="button" value="Refresh" onclick="document.location.reload()" />
    <hr />
    <br />
    <h2>
        Active</h2>
    <table>
        <tr class="Header">
            <td>
                ID
            </td>
            <td>
                Title
            </td>
            <td>
                Created
            </td>
            <td>
                Status
            </td>
            <td>
                Invited Vendors
            </td>
            <td>
                View as...
            </td>
        </tr>
        @foreach (var rfp in Model)
        {
            <tr>
                <td>
                    @rfp.ID.ToString()
                </td>
                <td>
                    @rfp.Title
                </td>
                <td>
                    @rfp.CreationDate
                </td>
                <td>
                    @rfp.Status
                </td>
                <td>
                    @rfp.GetInvitedVendorsStatus(true)
                </td>
                <td>
                    <select id="sel_@(rfp.ID.ToString())">
                        <option value="1">Vendor 1</option>
                        <option value="2">Vendor 2</option>
                        <option value="3">Vendor 3</option>
                        <option value="4">Vendor 4</option>
                        <option value="5">Vendor 5</option>
                        <option value="6">Vendor 6</option>
                        <option value="7">Vendor 7</option>
                        <option value="8">Vendor 8</option>
                        <option value="">Requestor</option>
                    </select><input type="button" value="View" onclick="showProposal('@rfp.ID.ToString()')" />
                </td>
            </tr>
        }
    </table>
    <br />
    @{Html.RenderAction("FinishedProposals", "Purchasing");}
</div>

solution/Adventureworks.WebMVC3/Views/Purchasing/VendorProposal.cshtml
@model Adventureworks.Domain.RequestForProposal
@{
    ViewBag.Title = "VendorProposal";
}
<h2>
    VendorProposal</h2>
@using (Html.BeginForm())
{
    <input type="hidden" name="ID" value="@Model.ID" />
    <input type="hidden" name="VendorId" value="@ViewBag.VendorId" />
    <div>
        <h1>
            Purchase Process Sample - Best Vendor Selection</h1>
        This screen is used by the vendors for submiting proposals to the RFP.
        <hr />
        <h2>
            Introduce your Offer</h2>
        <h3>
            RFP Details</h3>
        <table id="formTable">
            <tr>
                <td>
                    Title
                </td>
                <td>
                    <span id="lblTitle" style="font-family: Calibri,Arial;">test</span>
                </td>
            </tr>
            <tr>
                <td>
                    Description
                </td>
                <td>
                    <span id="lblDescription" style="font-family: Calibri,Arial;">test description</span>
                </td>
            </tr>
            <tr>
                <td>
                    Created
                </td>
                <td>
                    <span id="lblCreated" style="font-family: Calibri,Arial;">3/11/2011 2:50:58 PM</span>
                </td>
            </tr>
        </table>
        <br />
        <div id="pnlVendorOffer">
            <h3>
                Introduce your Proposal</h3>
            <table>
                <tr>
                    <td>
                        Value
                    </td>
                    <td>
                        <input name="Value" type="text" size="8" id="txtProposal" />
                        USD
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="center">
                        <br />
                        <input type="button" value="Go Back" onclick="document.location='default.aspx';" />
                        <input type="submit" name="btnCreate" value="Submit Offer" id="btnCreate" />
                    </td>
                </tr>
            </table>
        </div>
        <br />
    </div>
}